services:
  discord-bot:
    build:
      context: ./
      args:
        TZ: "${TZ:-Europe/Berlin}"
    environment:
      TOKEN: "${TOKEN:?No discord token passed}"
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data: